#!/bin/sh

if [ -f build/libs/sudoku-uber.jar ]; then
  exec java -cp build/libs/sudoku-uber.jar net.tommay.sudoku.Solve "$@"
else
  exec scala -cp build/libs/sudoku.jar net.tommay.sudoku.Solve "$@"
fi
