/*
  Source code is in UTF-8 encoding. The following symbols may appear, among others:
  α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ ς σ τ υ φ χ ψ ω « • ¦ » ∀ ∃ ∷ … → ← ﬁ ﬂ ƒ
  If you can't read this, you're out of luck. This code was generated with the frege compiler version 3.24.141
  from ./net/tommay/sudoku/Step.fr Do not edit this file! Instead, edit the source file and recompile.
*/

package net.tommay.sudoku;

import frege.run7.Func;
import frege.run7.Lazy;
import frege.run7.Thunk;
import frege.run.Kind;
import frege.run.RunTM;
import frege.runtime.Meta;
import frege.runtime.Phantom.RealWorld;
import frege.Prelude;
import frege.control.Category;
import frege.control.Semigroupoid;
import frege.data.Bits;
import frege.data.Char;
import frege.data.Foldable;
import frege.data.HashMap;
import frege.data.Iterators;
import frege.data.JSON;
import frege.data.List;
import frege.data.MicroParsec;
import frege.data.Monoid;
import frege.data.Traversable;
import frege.data.wrapper.Const;
import frege.data.wrapper.Dual;
import frege.data.wrapper.Endo;
import frege.data.wrapper.Identity;
import frege.data.wrapper.Num;
import frege.java.IO;
import frege.java.Lang;
import frege.java.Util;
import frege.java.util.Regex;
import frege.lib.PP;
import frege.prelude.Maybe;
import frege.prelude.PreludeArrays;
import frege.prelude.PreludeBase;
import frege.prelude.PreludeIO;
import frege.prelude.PreludeList;
import frege.prelude.PreludeMonad;
import frege.prelude.PreludeText;
import frege.system.Random;
import net.tommay.sudoku.Digit;
import net.tommay.sudoku.Placement;
import net.tommay.sudoku.Puzzle;

@SuppressWarnings("unused")
@Meta.FregePackage(
  source="./net/tommay/sudoku/Step.fr", time=1481937171196L, jmajor=1, jminor=7,
  imps={
    "net.tommay.sudoku.Placement", "frege.Prelude", "frege.prelude.PreludeArrays", "frege.prelude.PreludeBase",
    "frege.prelude.PreludeIO", "frege.prelude.PreludeList", "frege.prelude.PreludeMonad", "frege.prelude.PreludeText",
    "net.tommay.sudoku.Puzzle", "frege.java.util.Regex"
  },
  nmss={
    "Placement", "Prelude", "PreludeArrays", "PreludeBase", "PreludeIO", "PreludeList", "PreludeMonad",
    "PreludeText", "Puzzle", "Regexp"
  },
  symas={}, symcs={}, symis={},
  symts={
    @Meta.SymT(
      offset=131, name=@Meta.QName(kind=0, pack="net.tommay.sudoku.Step", base="Step"), typ=0,
      kind=8,
      cons={
        @Meta.SymD(
          offset=138, name=@Meta.QName(kind=2, pack="net.tommay.sudoku.Step", base="Step", member="Step"), cid=0,
          typ=4,
          fields={
            @Meta.Field(offset=0, sigma=1, strict=false), @Meta.Field(offset=0, sigma=2, strict=false),
            @Meta.Field(offset=0, sigma=3, strict=false)
          }
        )
      },
      lnks={}, funs={}, prod=true
    )
  },
  symvs={},
  symls={
    @Meta.SymL(
      offset=138, name=@Meta.QName(pack="net.tommay.sudoku.Step", base="Step"),
      alias=@Meta.QName(kind=2, pack="net.tommay.sudoku.Step", base="Step", member="Step")
    )
  },
  taus={
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="net.tommay.sudoku.Step", base="Step")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="net.tommay.sudoku.Puzzle", base="Puzzle")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Maybe")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="net.tommay.sudoku.Placement", base="Placement")}),
    @Meta.Tau(kind=0, suba=2, subb=3),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="StringJ")}),
    @Meta.Tau(kind=2, suba=0, tcon={@Meta.QName(kind=0, pack="frege.prelude.PreludeBase", base="Char")}),
    @Meta.Tau(kind=0, suba=5, subb=6), @Meta.Tau(kind=9)
  },
  rhos={
    @Meta.Rho(rhofun=false, rhotau=0), @Meta.Rho(rhofun=false, rhotau=1), @Meta.Rho(rhofun=false, rhotau=4),
    @Meta.Rho(rhofun=false, rhotau=7), @Meta.Rho(sigma=3, rhotau=0), @Meta.Rho(sigma=2, rhotau=4),
    @Meta.Rho(sigma=1, rhotau=5)
  },
  sigmas={@Meta.Sigma(rho=0), @Meta.Sigma(rho=1), @Meta.Sigma(rho=2), @Meta.Sigma(rho=3), @Meta.Sigma(rho=6)},
  exprs={@Meta.Expr()}
)
final public class Step  {
  



final public static class TStep implements frege.runtime.Value, Lazy<TStep> {
  private TStep(
    final Lazy<Puzzle.TPuzzle> arg$1, final Lazy<PreludeBase.TMaybe<Placement.TPlacement>> arg$2,
    final Lazy<String/*<Character>*/> arg$3
  ) {
    mem1 = Thunk.<Puzzle.TPuzzle>shared(arg$1);
    mem2 = Thunk.<PreludeBase.TMaybe<Placement.TPlacement>>shared(arg$2);
    mem3 = Thunk.<String/*<Character>*/>shared(arg$3);
  }
  final public int constructor() {
    return 0;
  }
  final public static TStep mk(
    final Lazy<Puzzle.TPuzzle> arg$1, final Lazy<PreludeBase.TMaybe<Placement.TPlacement>> arg$2,
    final Lazy<String/*<Character>*/> arg$3
  ) {
    return new TStep(arg$1, arg$2, arg$3);
  }
  final public Lazy<Puzzle.TPuzzle> mem1  ;
  final public Lazy<PreludeBase.TMaybe<Placement.TPlacement>> mem2  ;
  final public Lazy<String/*<Character>*/> mem3  ;
  final public TStep call() {
    return this;
  }
  final public boolean isShared() {
    return true;
  }
  final public Thunk<TStep> asThunk() {
    return null;
  }
  @SuppressWarnings("unchecked") final public TStep simsalabim() {
    return (TStep)this;
  }
}


}
